### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'Layer'

### ISSUE THREAD

**Issue by emibarrod** [Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0#15]
Hi! I'm trying to train a custom dataset and I encountered a problem.

In `module.py` there are some classes that uses `KE.Layers` (where KE is keras.engine). For example:
```python
class ProposalLayer(KE.Layer):
``` 

Giving me this error:
```
  File "/home/emilio/project/mask-rcnn-tf2.7/mrcnn/model.py", line 256, in <module>
    class ProposalLayer(KE.Layer):
AttributeError: module 'keras.engine' has no attribute 'Layer'
```

It looks like `Layers` is now in `keras.layers.Layer` but, if I change KE to KL in the code, the following error appears:
```
Traceback (most recent call last):
  File "color_bands.py", line 308, in <module>
    model = modellib.MaskRCNN(mode="training", config=config,
  File "/home/emilio/project/mask-rcnn-tf2.7/mrcnn/model.py", line 1847, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/emilio/project/mask-rcnn-tf2.7/mrcnn/model.py", line 1885, in build
    gt_boxes = KL.Lambda(lambda x: norm_boxes_graph(
  File "/home/emilio/tf2.7/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/emilio/tf2.7/lib/python3.8/site-packages/tensorflow/python/framework/type_spec.py", line 867, in type_spec_from_value
    raise TypeError(f"Could not build a TypeSpec for {value} of "
TypeError: Could not build a TypeSpec for KerasTensor(type_spec=TensorSpec(shape=(None, None, 4), dtype=tf.float32, name=None), name='tf.math.truediv/truediv:0', description="created by layer 'tf.math.truediv'") of unsupported type <class 'keras.engine.keras_tensor.KerasTensor'>.
```

Any hints or fixes? Thanks in advance!

**Comment by emibarrod** [comment]
I was using the wrong script.
